# Generated from pyproject.toml - do not edit by hand.
# Regenerated by scripts/write-version.py / the hatchling build hook whenever
# the version changes (see packaging/versioning.py).
__version__ = "0.0.1"
__version_tuple__ = (0, 0, 1)
