"""Single-source version plumbing for the build pipeline.

`pyproject.toml` is the only hand-edited version. This module regenerates
``src/comic_dl/_version.py`` from it so every artifact (wheel, sdist, distro
packages, PyInstaller binaries) embeds the same value without relying on
``importlib.metadata`` (which does not exist inside a PyInstaller bundle).

Consumers:
  - ``scripts/write-version.py`` — explicit regeneration / ``--check`` drift guard
  - ``packaging/hatch/version_hook.py`` — regenerates before every hatchling build

The checked-in ``_version.py`` is deliberately tracked (not gitignored) so a
fresh checkout builds and reports a correct version before any build runs; a
version bump must ship with its regenerated file (enforced by the ``--check``
guard and ``tests/test_version.py``).
"""

from __future__ import annotations

import re
import tomllib
from pathlib import Path

HEADER = """\
# Generated from pyproject.toml - do not edit by hand.
# Regenerated by scripts/write-version.py / the hatchling build hook whenever
# the version changes (see packaging/versioning.py).
"""


def project_version(pyproject_path: Path) -> str:
    """``[project].version`` from a ``pyproject.toml``."""
    with pyproject_path.open("rb") as fh:
        data = tomllib.load(fh)
    project = data["project"]
    version = project["version"]
    if not isinstance(version, str) or not version.strip():
        raise ValueError(f"{pyproject_path}: [project].version is not a non-empty string")
    return version.strip()


def _version_tuple(version: str) -> tuple[int, ...]:
    """Leading integer segments of the version (``1.0.0rc1`` -> ``(1, 0, 0)``).

    Keeps one entry per release segment so ordering-friendly consumers get a
    stable shape; pre-release/post-release text is dropped.
    """
    out: list[int] = []
    for segment in version.split("."):
        match = re.match(r"\d+", segment)
        if match is None:
            break
        out.append(int(match.group()))
    return tuple(out)


def render_version_file(version: str) -> str:
    """File text for ``_version.py`` given a PEP 440 version string."""
    members = ", ".join(str(part) for part in _version_tuple(version))
    if not members:
        members = "0"
    return f'{HEADER}__version__ = "{version}"\n__version_tuple__ = ({members})\n'


def write_version_file(pyproject_path: Path, version_out_path: Path) -> str:
    """Regenerate ``version_out_path`` from ``pyproject_path``; returns the version."""
    version = project_version(pyproject_path)
    version_out_path.parent.mkdir(parents=True, exist_ok=True)
    version_out_path.write_text(render_version_file(version), encoding="utf-8")
    return version


def check_version_file(pyproject_path: Path, version_out_path: Path) -> str | None:
    """None when ``version_out_path`` matches ``pyproject_path``; else a reason.

    Returns a description of the first mismatch so callers (CI drift guard,
    tests) can explain why the build failed.
    """
    try:
        version = project_version(pyproject_path)
    except (OSError, KeyError, TypeError, tomllib.TOMLDecodeError) as exc:
        return f"cannot read {pyproject_path}: {exc}"
    try:
        actual = version_out_path.read_text(encoding="utf-8")
    except OSError as exc:
        return f"{version_out_path} is missing or unreadable: {exc}"
    if actual != render_version_file(version):
        return (
            f"{version_out_path} is out of date (expected version {version!r}). "
            "Run `uv run scripts/write-version.py` and commit the result."
        )
    return None
